// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: internal/proto/netem.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Netem_ServerGetVersion_FullMethodName      = "/netem.Netem/ServerGetVersion"
	Netem_ServerPullImages_FullMethodName      = "/netem.Netem/ServerPullImages"
	Netem_ServerCleanContainers_FullMethodName = "/netem.Netem/ServerCleanContainers"
	Netem_ProjectGetMany_FullMethodName        = "/netem.Netem/ProjectGetMany"
	Netem_ProjectOpen_FullMethodName           = "/netem.Netem/ProjectOpen"
	Netem_ProjectClose_FullMethodName          = "/netem.Netem/ProjectClose"
	Netem_ProjectSave_FullMethodName           = "/netem.Netem/ProjectSave"
	Netem_ProjectGetNodeConfigs_FullMethodName = "/netem.Netem/ProjectGetNodeConfigs"
	Netem_ProjectGetStatus_FullMethodName      = "/netem.Netem/ProjectGetStatus"
	Netem_ReadNetworkFile_FullMethodName       = "/netem.Netem/ReadNetworkFile"
	Netem_WriteNetworkFile_FullMethodName      = "/netem.Netem/WriteNetworkFile"
	Netem_TopologyCheck_FullMethodName         = "/netem.Netem/TopologyCheck"
	Netem_TopologyReload_FullMethodName        = "/netem.Netem/TopologyReload"
	Netem_TopologyRun_FullMethodName           = "/netem.Netem/TopologyRun"
	Netem_TopologyStartAll_FullMethodName      = "/netem.Netem/TopologyStartAll"
	Netem_TopologyStopAll_FullMethodName       = "/netem.Netem/TopologyStopAll"
	Netem_NodeReadConfigFiles_FullMethodName   = "/netem.Netem/NodeReadConfigFiles"
	Netem_NodeStart_FullMethodName             = "/netem.Netem/NodeStart"
	Netem_NodeStop_FullMethodName              = "/netem.Netem/NodeStop"
	Netem_NodeRestart_FullMethodName           = "/netem.Netem/NodeRestart"
	Netem_NodeSetIfState_FullMethodName        = "/netem.Netem/NodeSetIfState"
	Netem_NodeCapture_FullMethodName           = "/netem.Netem/NodeCapture"
	Netem_NodeCopyFrom_FullMethodName          = "/netem.Netem/NodeCopyFrom"
	Netem_NodeCopyTo_FullMethodName            = "/netem.Netem/NodeCopyTo"
	Netem_NodeGetConsoleCmd_FullMethodName     = "/netem.Netem/NodeGetConsoleCmd"
	Netem_NodeRun_FullMethodName               = "/netem.Netem/NodeRun"
	Netem_NodeExec_FullMethodName              = "/netem.Netem/NodeExec"
	Netem_LinkUpdate_FullMethodName            = "/netem.Netem/LinkUpdate"
	Netem_LinkAdd_FullMethodName               = "/netem.Netem/LinkAdd"
	Netem_LinkDel_FullMethodName               = "/netem.Netem/LinkDel"
)

// NetemClient is the client API for Netem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetemClient interface {
	// Server actions
	ServerGetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	ServerPullImages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullSrvMsg], error)
	ServerCleanContainers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AckResponse, error)
	// Project actions
	ProjectGetMany(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PrjListResponse, error)
	ProjectOpen(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*PrjOpenResponse, error)
	ProjectClose(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectCloseMsg], error)
	ProjectSave(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectSaveMsg], error)
	ProjectGetNodeConfigs(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*FileResponse, error)
	ProjectGetStatus(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Read/Write network topology
	ReadNetworkFile(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*FileResponse, error)
	WriteNetworkFile(ctx context.Context, in *WNetworkRequest, opts ...grpc.CallOption) (*AckResponse, error)
	// topology actions
	TopologyCheck(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*AckResponse, error)
	TopologyReload(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopologyRunMsg], error)
	TopologyRun(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopologyRunMsg], error)
	TopologyStartAll(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*AckResponse, error)
	TopologyStopAll(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*AckResponse, error)
	// Node actions
	NodeReadConfigFiles(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*ConfigFilesResponse, error)
	NodeStart(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AckResponse, error)
	NodeStop(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AckResponse, error)
	NodeRestart(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AckResponse, error)
	NodeSetIfState(ctx context.Context, in *NodeIfStateRequest, opts ...grpc.CallOption) (*AckResponse, error)
	NodeCapture(ctx context.Context, in *NodeInterfaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CaptureSrvMsg], error)
	NodeCopyFrom(ctx context.Context, in *CopyMsg, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyMsg], error)
	NodeCopyTo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyMsg, AckResponse], error)
	NodeGetConsoleCmd(ctx context.Context, in *ConsoleCmdRequest, opts ...grpc.CallOption) (*ConsoleCmdResponse, error)
	NodeRun(ctx context.Context, in *NodeRunRequest, opts ...grpc.CallOption) (*NodeRunResponse, error)
	NodeExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecCltMsg, ExecSrvMsg], error)
	// Link actions
	LinkUpdate(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*AckResponse, error)
	LinkAdd(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*AckResponse, error)
	LinkDel(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*AckResponse, error)
}

type netemClient struct {
	cc grpc.ClientConnInterface
}

func NewNetemClient(cc grpc.ClientConnInterface) NetemClient {
	return &netemClient{cc}
}

func (c *netemClient) ServerGetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, Netem_ServerGetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) ServerPullImages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullSrvMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[0], Netem_ServerPullImages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[empty.Empty, PullSrvMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_ServerPullImagesClient = grpc.ServerStreamingClient[PullSrvMsg]

func (c *netemClient) ServerCleanContainers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_ServerCleanContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) ProjectGetMany(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PrjListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrjListResponse)
	err := c.cc.Invoke(ctx, Netem_ProjectGetMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) ProjectOpen(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*PrjOpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrjOpenResponse)
	err := c.cc.Invoke(ctx, Netem_ProjectOpen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) ProjectClose(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectCloseMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[1], Netem_ProjectClose_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectRequest, ProjectCloseMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_ProjectCloseClient = grpc.ServerStreamingClient[ProjectCloseMsg]

func (c *netemClient) ProjectSave(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectSaveMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[2], Netem_ProjectSave_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectRequest, ProjectSaveMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_ProjectSaveClient = grpc.ServerStreamingClient[ProjectSaveMsg]

func (c *netemClient) ProjectGetNodeConfigs(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, Netem_ProjectGetNodeConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) ProjectGetStatus(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Netem_ProjectGetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) ReadNetworkFile(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, Netem_ReadNetworkFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) WriteNetworkFile(ctx context.Context, in *WNetworkRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_WriteNetworkFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) TopologyCheck(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_TopologyCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) TopologyReload(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopologyRunMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[3], Netem_TopologyReload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectRequest, TopologyRunMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_TopologyReloadClient = grpc.ServerStreamingClient[TopologyRunMsg]

func (c *netemClient) TopologyRun(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopologyRunMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[4], Netem_TopologyRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectRequest, TopologyRunMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_TopologyRunClient = grpc.ServerStreamingClient[TopologyRunMsg]

func (c *netemClient) TopologyStartAll(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_TopologyStartAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) TopologyStopAll(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_TopologyStopAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) NodeReadConfigFiles(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*ConfigFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigFilesResponse)
	err := c.cc.Invoke(ctx, Netem_NodeReadConfigFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) NodeStart(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_NodeStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) NodeStop(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_NodeStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) NodeRestart(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_NodeRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) NodeSetIfState(ctx context.Context, in *NodeIfStateRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_NodeSetIfState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) NodeCapture(ctx context.Context, in *NodeInterfaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CaptureSrvMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[5], Netem_NodeCapture_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeInterfaceRequest, CaptureSrvMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_NodeCaptureClient = grpc.ServerStreamingClient[CaptureSrvMsg]

func (c *netemClient) NodeCopyFrom(ctx context.Context, in *CopyMsg, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[6], Netem_NodeCopyFrom_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyMsg, CopyMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_NodeCopyFromClient = grpc.ServerStreamingClient[CopyMsg]

func (c *netemClient) NodeCopyTo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyMsg, AckResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[7], Netem_NodeCopyTo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyMsg, AckResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_NodeCopyToClient = grpc.ClientStreamingClient[CopyMsg, AckResponse]

func (c *netemClient) NodeGetConsoleCmd(ctx context.Context, in *ConsoleCmdRequest, opts ...grpc.CallOption) (*ConsoleCmdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleCmdResponse)
	err := c.cc.Invoke(ctx, Netem_NodeGetConsoleCmd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) NodeRun(ctx context.Context, in *NodeRunRequest, opts ...grpc.CallOption) (*NodeRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRunResponse)
	err := c.cc.Invoke(ctx, Netem_NodeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) NodeExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecCltMsg, ExecSrvMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Netem_ServiceDesc.Streams[8], Netem_NodeExec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecCltMsg, ExecSrvMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_NodeExecClient = grpc.BidiStreamingClient[ExecCltMsg, ExecSrvMsg]

func (c *netemClient) LinkUpdate(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_LinkUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) LinkAdd(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_LinkAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netemClient) LinkDel(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Netem_LinkDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetemServer is the server API for Netem service.
// All implementations must embed UnimplementedNetemServer
// for forward compatibility.
type NetemServer interface {
	// Server actions
	ServerGetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
	ServerPullImages(*empty.Empty, grpc.ServerStreamingServer[PullSrvMsg]) error
	ServerCleanContainers(context.Context, *empty.Empty) (*AckResponse, error)
	// Project actions
	ProjectGetMany(context.Context, *empty.Empty) (*PrjListResponse, error)
	ProjectOpen(context.Context, *OpenRequest) (*PrjOpenResponse, error)
	ProjectClose(*ProjectRequest, grpc.ServerStreamingServer[ProjectCloseMsg]) error
	ProjectSave(*ProjectRequest, grpc.ServerStreamingServer[ProjectSaveMsg]) error
	ProjectGetNodeConfigs(context.Context, *ProjectRequest) (*FileResponse, error)
	ProjectGetStatus(context.Context, *ProjectRequest) (*StatusResponse, error)
	// Read/Write network topology
	ReadNetworkFile(context.Context, *ProjectRequest) (*FileResponse, error)
	WriteNetworkFile(context.Context, *WNetworkRequest) (*AckResponse, error)
	// topology actions
	TopologyCheck(context.Context, *ProjectRequest) (*AckResponse, error)
	TopologyReload(*ProjectRequest, grpc.ServerStreamingServer[TopologyRunMsg]) error
	TopologyRun(*ProjectRequest, grpc.ServerStreamingServer[TopologyRunMsg]) error
	TopologyStartAll(context.Context, *ProjectRequest) (*AckResponse, error)
	TopologyStopAll(context.Context, *ProjectRequest) (*AckResponse, error)
	// Node actions
	NodeReadConfigFiles(context.Context, *NodeRequest) (*ConfigFilesResponse, error)
	NodeStart(context.Context, *NodeRequest) (*AckResponse, error)
	NodeStop(context.Context, *NodeRequest) (*AckResponse, error)
	NodeRestart(context.Context, *NodeRequest) (*AckResponse, error)
	NodeSetIfState(context.Context, *NodeIfStateRequest) (*AckResponse, error)
	NodeCapture(*NodeInterfaceRequest, grpc.ServerStreamingServer[CaptureSrvMsg]) error
	NodeCopyFrom(*CopyMsg, grpc.ServerStreamingServer[CopyMsg]) error
	NodeCopyTo(grpc.ClientStreamingServer[CopyMsg, AckResponse]) error
	NodeGetConsoleCmd(context.Context, *ConsoleCmdRequest) (*ConsoleCmdResponse, error)
	NodeRun(context.Context, *NodeRunRequest) (*NodeRunResponse, error)
	NodeExec(grpc.BidiStreamingServer[ExecCltMsg, ExecSrvMsg]) error
	// Link actions
	LinkUpdate(context.Context, *LinkRequest) (*AckResponse, error)
	LinkAdd(context.Context, *LinkRequest) (*AckResponse, error)
	LinkDel(context.Context, *LinkRequest) (*AckResponse, error)
	mustEmbedUnimplementedNetemServer()
}

// UnimplementedNetemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetemServer struct{}

func (UnimplementedNetemServer) ServerGetVersion(context.Context, *empty.Empty) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerGetVersion not implemented")
}
func (UnimplementedNetemServer) ServerPullImages(*empty.Empty, grpc.ServerStreamingServer[PullSrvMsg]) error {
	return status.Error(codes.Unimplemented, "method ServerPullImages not implemented")
}
func (UnimplementedNetemServer) ServerCleanContainers(context.Context, *empty.Empty) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerCleanContainers not implemented")
}
func (UnimplementedNetemServer) ProjectGetMany(context.Context, *empty.Empty) (*PrjListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProjectGetMany not implemented")
}
func (UnimplementedNetemServer) ProjectOpen(context.Context, *OpenRequest) (*PrjOpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProjectOpen not implemented")
}
func (UnimplementedNetemServer) ProjectClose(*ProjectRequest, grpc.ServerStreamingServer[ProjectCloseMsg]) error {
	return status.Error(codes.Unimplemented, "method ProjectClose not implemented")
}
func (UnimplementedNetemServer) ProjectSave(*ProjectRequest, grpc.ServerStreamingServer[ProjectSaveMsg]) error {
	return status.Error(codes.Unimplemented, "method ProjectSave not implemented")
}
func (UnimplementedNetemServer) ProjectGetNodeConfigs(context.Context, *ProjectRequest) (*FileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProjectGetNodeConfigs not implemented")
}
func (UnimplementedNetemServer) ProjectGetStatus(context.Context, *ProjectRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProjectGetStatus not implemented")
}
func (UnimplementedNetemServer) ReadNetworkFile(context.Context, *ProjectRequest) (*FileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadNetworkFile not implemented")
}
func (UnimplementedNetemServer) WriteNetworkFile(context.Context, *WNetworkRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteNetworkFile not implemented")
}
func (UnimplementedNetemServer) TopologyCheck(context.Context, *ProjectRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopologyCheck not implemented")
}
func (UnimplementedNetemServer) TopologyReload(*ProjectRequest, grpc.ServerStreamingServer[TopologyRunMsg]) error {
	return status.Error(codes.Unimplemented, "method TopologyReload not implemented")
}
func (UnimplementedNetemServer) TopologyRun(*ProjectRequest, grpc.ServerStreamingServer[TopologyRunMsg]) error {
	return status.Error(codes.Unimplemented, "method TopologyRun not implemented")
}
func (UnimplementedNetemServer) TopologyStartAll(context.Context, *ProjectRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopologyStartAll not implemented")
}
func (UnimplementedNetemServer) TopologyStopAll(context.Context, *ProjectRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopologyStopAll not implemented")
}
func (UnimplementedNetemServer) NodeReadConfigFiles(context.Context, *NodeRequest) (*ConfigFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeReadConfigFiles not implemented")
}
func (UnimplementedNetemServer) NodeStart(context.Context, *NodeRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeStart not implemented")
}
func (UnimplementedNetemServer) NodeStop(context.Context, *NodeRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeStop not implemented")
}
func (UnimplementedNetemServer) NodeRestart(context.Context, *NodeRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeRestart not implemented")
}
func (UnimplementedNetemServer) NodeSetIfState(context.Context, *NodeIfStateRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeSetIfState not implemented")
}
func (UnimplementedNetemServer) NodeCapture(*NodeInterfaceRequest, grpc.ServerStreamingServer[CaptureSrvMsg]) error {
	return status.Error(codes.Unimplemented, "method NodeCapture not implemented")
}
func (UnimplementedNetemServer) NodeCopyFrom(*CopyMsg, grpc.ServerStreamingServer[CopyMsg]) error {
	return status.Error(codes.Unimplemented, "method NodeCopyFrom not implemented")
}
func (UnimplementedNetemServer) NodeCopyTo(grpc.ClientStreamingServer[CopyMsg, AckResponse]) error {
	return status.Error(codes.Unimplemented, "method NodeCopyTo not implemented")
}
func (UnimplementedNetemServer) NodeGetConsoleCmd(context.Context, *ConsoleCmdRequest) (*ConsoleCmdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeGetConsoleCmd not implemented")
}
func (UnimplementedNetemServer) NodeRun(context.Context, *NodeRunRequest) (*NodeRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeRun not implemented")
}
func (UnimplementedNetemServer) NodeExec(grpc.BidiStreamingServer[ExecCltMsg, ExecSrvMsg]) error {
	return status.Error(codes.Unimplemented, "method NodeExec not implemented")
}
func (UnimplementedNetemServer) LinkUpdate(context.Context, *LinkRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkUpdate not implemented")
}
func (UnimplementedNetemServer) LinkAdd(context.Context, *LinkRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkAdd not implemented")
}
func (UnimplementedNetemServer) LinkDel(context.Context, *LinkRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkDel not implemented")
}
func (UnimplementedNetemServer) mustEmbedUnimplementedNetemServer() {}
func (UnimplementedNetemServer) testEmbeddedByValue()               {}

// UnsafeNetemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetemServer will
// result in compilation errors.
type UnsafeNetemServer interface {
	mustEmbedUnimplementedNetemServer()
}

func RegisterNetemServer(s grpc.ServiceRegistrar, srv NetemServer) {
	// If the following call panics, it indicates UnimplementedNetemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Netem_ServiceDesc, srv)
}

func _Netem_ServerGetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).ServerGetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_ServerGetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).ServerGetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_ServerPullImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetemServer).ServerPullImages(m, &grpc.GenericServerStream[empty.Empty, PullSrvMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_ServerPullImagesServer = grpc.ServerStreamingServer[PullSrvMsg]

func _Netem_ServerCleanContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).ServerCleanContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_ServerCleanContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).ServerCleanContainers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_ProjectGetMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).ProjectGetMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_ProjectGetMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).ProjectGetMany(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_ProjectOpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).ProjectOpen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_ProjectOpen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).ProjectOpen(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_ProjectClose_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetemServer).ProjectClose(m, &grpc.GenericServerStream[ProjectRequest, ProjectCloseMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_ProjectCloseServer = grpc.ServerStreamingServer[ProjectCloseMsg]

func _Netem_ProjectSave_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetemServer).ProjectSave(m, &grpc.GenericServerStream[ProjectRequest, ProjectSaveMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_ProjectSaveServer = grpc.ServerStreamingServer[ProjectSaveMsg]

func _Netem_ProjectGetNodeConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).ProjectGetNodeConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_ProjectGetNodeConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).ProjectGetNodeConfigs(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_ProjectGetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).ProjectGetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_ProjectGetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).ProjectGetStatus(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_ReadNetworkFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).ReadNetworkFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_ReadNetworkFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).ReadNetworkFile(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_WriteNetworkFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).WriteNetworkFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_WriteNetworkFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).WriteNetworkFile(ctx, req.(*WNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_TopologyCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).TopologyCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_TopologyCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).TopologyCheck(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_TopologyReload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetemServer).TopologyReload(m, &grpc.GenericServerStream[ProjectRequest, TopologyRunMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_TopologyReloadServer = grpc.ServerStreamingServer[TopologyRunMsg]

func _Netem_TopologyRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetemServer).TopologyRun(m, &grpc.GenericServerStream[ProjectRequest, TopologyRunMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_TopologyRunServer = grpc.ServerStreamingServer[TopologyRunMsg]

func _Netem_TopologyStartAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).TopologyStartAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_TopologyStartAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).TopologyStartAll(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_TopologyStopAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).TopologyStopAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_TopologyStopAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).TopologyStopAll(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_NodeReadConfigFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).NodeReadConfigFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_NodeReadConfigFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).NodeReadConfigFiles(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_NodeStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).NodeStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_NodeStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).NodeStart(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_NodeStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).NodeStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_NodeStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).NodeStop(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_NodeRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).NodeRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_NodeRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).NodeRestart(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_NodeSetIfState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIfStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).NodeSetIfState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_NodeSetIfState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).NodeSetIfState(ctx, req.(*NodeIfStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_NodeCapture_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NodeInterfaceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetemServer).NodeCapture(m, &grpc.GenericServerStream[NodeInterfaceRequest, CaptureSrvMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_NodeCaptureServer = grpc.ServerStreamingServer[CaptureSrvMsg]

func _Netem_NodeCopyFrom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CopyMsg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetemServer).NodeCopyFrom(m, &grpc.GenericServerStream[CopyMsg, CopyMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_NodeCopyFromServer = grpc.ServerStreamingServer[CopyMsg]

func _Netem_NodeCopyTo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetemServer).NodeCopyTo(&grpc.GenericServerStream[CopyMsg, AckResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_NodeCopyToServer = grpc.ClientStreamingServer[CopyMsg, AckResponse]

func _Netem_NodeGetConsoleCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsoleCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).NodeGetConsoleCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_NodeGetConsoleCmd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).NodeGetConsoleCmd(ctx, req.(*ConsoleCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_NodeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).NodeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_NodeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).NodeRun(ctx, req.(*NodeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_NodeExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetemServer).NodeExec(&grpc.GenericServerStream[ExecCltMsg, ExecSrvMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Netem_NodeExecServer = grpc.BidiStreamingServer[ExecCltMsg, ExecSrvMsg]

func _Netem_LinkUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).LinkUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_LinkUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).LinkUpdate(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_LinkAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).LinkAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_LinkAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).LinkAdd(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netem_LinkDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetemServer).LinkDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Netem_LinkDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetemServer).LinkDel(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Netem_ServiceDesc is the grpc.ServiceDesc for Netem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Netem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netem.Netem",
	HandlerType: (*NetemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerGetVersion",
			Handler:    _Netem_ServerGetVersion_Handler,
		},
		{
			MethodName: "ServerCleanContainers",
			Handler:    _Netem_ServerCleanContainers_Handler,
		},
		{
			MethodName: "ProjectGetMany",
			Handler:    _Netem_ProjectGetMany_Handler,
		},
		{
			MethodName: "ProjectOpen",
			Handler:    _Netem_ProjectOpen_Handler,
		},
		{
			MethodName: "ProjectGetNodeConfigs",
			Handler:    _Netem_ProjectGetNodeConfigs_Handler,
		},
		{
			MethodName: "ProjectGetStatus",
			Handler:    _Netem_ProjectGetStatus_Handler,
		},
		{
			MethodName: "ReadNetworkFile",
			Handler:    _Netem_ReadNetworkFile_Handler,
		},
		{
			MethodName: "WriteNetworkFile",
			Handler:    _Netem_WriteNetworkFile_Handler,
		},
		{
			MethodName: "TopologyCheck",
			Handler:    _Netem_TopologyCheck_Handler,
		},
		{
			MethodName: "TopologyStartAll",
			Handler:    _Netem_TopologyStartAll_Handler,
		},
		{
			MethodName: "TopologyStopAll",
			Handler:    _Netem_TopologyStopAll_Handler,
		},
		{
			MethodName: "NodeReadConfigFiles",
			Handler:    _Netem_NodeReadConfigFiles_Handler,
		},
		{
			MethodName: "NodeStart",
			Handler:    _Netem_NodeStart_Handler,
		},
		{
			MethodName: "NodeStop",
			Handler:    _Netem_NodeStop_Handler,
		},
		{
			MethodName: "NodeRestart",
			Handler:    _Netem_NodeRestart_Handler,
		},
		{
			MethodName: "NodeSetIfState",
			Handler:    _Netem_NodeSetIfState_Handler,
		},
		{
			MethodName: "NodeGetConsoleCmd",
			Handler:    _Netem_NodeGetConsoleCmd_Handler,
		},
		{
			MethodName: "NodeRun",
			Handler:    _Netem_NodeRun_Handler,
		},
		{
			MethodName: "LinkUpdate",
			Handler:    _Netem_LinkUpdate_Handler,
		},
		{
			MethodName: "LinkAdd",
			Handler:    _Netem_LinkAdd_Handler,
		},
		{
			MethodName: "LinkDel",
			Handler:    _Netem_LinkDel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerPullImages",
			Handler:       _Netem_ServerPullImages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProjectClose",
			Handler:       _Netem_ProjectClose_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProjectSave",
			Handler:       _Netem_ProjectSave_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TopologyReload",
			Handler:       _Netem_TopologyReload_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TopologyRun",
			Handler:       _Netem_TopologyRun_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "NodeCapture",
			Handler:       _Netem_NodeCapture_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "NodeCopyFrom",
			Handler:       _Netem_NodeCopyFrom_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "NodeCopyTo",
			Handler:       _Netem_NodeCopyTo_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "NodeExec",
			Handler:       _Netem_NodeExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/netem.proto",
}
