// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/proto/netem.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_OK    StatusCode = 0
	StatusCode_ERROR StatusCode = 1
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	StatusCode_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{0}
}

type IfState int32

const (
	IfState_UP   IfState = 0
	IfState_DOWN IfState = 1
)

// Enum value maps for IfState.
var (
	IfState_name = map[int32]string{
		0: "UP",
		1: "DOWN",
	}
	IfState_value = map[string]int32{
		"UP":   0,
		"DOWN": 1,
	}
)

func (x IfState) Enum() *IfState {
	p := new(IfState)
	*p = x
	return p
}

func (x IfState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IfState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[1].Descriptor()
}

func (IfState) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[1]
}

func (x IfState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IfState.Descriptor instead.
func (IfState) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{1}
}

type ExecCltMsg_Code int32

const (
	ExecCltMsg_CMD    ExecCltMsg_Code = 0
	ExecCltMsg_DATA   ExecCltMsg_Code = 1
	ExecCltMsg_RESIZE ExecCltMsg_Code = 2
	ExecCltMsg_ERROR  ExecCltMsg_Code = 3
	ExecCltMsg_CLOSE  ExecCltMsg_Code = 4
)

// Enum value maps for ExecCltMsg_Code.
var (
	ExecCltMsg_Code_name = map[int32]string{
		0: "CMD",
		1: "DATA",
		2: "RESIZE",
		3: "ERROR",
		4: "CLOSE",
	}
	ExecCltMsg_Code_value = map[string]int32{
		"CMD":    0,
		"DATA":   1,
		"RESIZE": 2,
		"ERROR":  3,
		"CLOSE":  4,
	}
)

func (x ExecCltMsg_Code) Enum() *ExecCltMsg_Code {
	p := new(ExecCltMsg_Code)
	*p = x
	return p
}

func (x ExecCltMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecCltMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[2].Descriptor()
}

func (ExecCltMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[2]
}

func (x ExecCltMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecCltMsg_Code.Descriptor instead.
func (ExecCltMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{0, 0}
}

type ExecSrvMsg_Code int32

const (
	ExecSrvMsg_STDOUT ExecSrvMsg_Code = 0
	ExecSrvMsg_STDERR ExecSrvMsg_Code = 1
	ExecSrvMsg_ERROR  ExecSrvMsg_Code = 2
	ExecSrvMsg_CLOSE  ExecSrvMsg_Code = 3
)

// Enum value maps for ExecSrvMsg_Code.
var (
	ExecSrvMsg_Code_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "ERROR",
		3: "CLOSE",
	}
	ExecSrvMsg_Code_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"ERROR":  2,
		"CLOSE":  3,
	}
)

func (x ExecSrvMsg_Code) Enum() *ExecSrvMsg_Code {
	p := new(ExecSrvMsg_Code)
	*p = x
	return p
}

func (x ExecSrvMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecSrvMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[3].Descriptor()
}

func (ExecSrvMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[3]
}

func (x ExecSrvMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecSrvMsg_Code.Descriptor instead.
func (ExecSrvMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{1, 0}
}

type CopyMsg_Code int32

const (
	CopyMsg_INIT  CopyMsg_Code = 0
	CopyMsg_DATA  CopyMsg_Code = 1
	CopyMsg_ERROR CopyMsg_Code = 3
)

// Enum value maps for CopyMsg_Code.
var (
	CopyMsg_Code_name = map[int32]string{
		0: "INIT",
		1: "DATA",
		3: "ERROR",
	}
	CopyMsg_Code_value = map[string]int32{
		"INIT":  0,
		"DATA":  1,
		"ERROR": 3,
	}
)

func (x CopyMsg_Code) Enum() *CopyMsg_Code {
	p := new(CopyMsg_Code)
	*p = x
	return p
}

func (x CopyMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[4].Descriptor()
}

func (CopyMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[4]
}

func (x CopyMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyMsg_Code.Descriptor instead.
func (CopyMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{2, 0}
}

type PullSrvMsg_Code int32

const (
	PullSrvMsg_START PullSrvMsg_Code = 0
	PullSrvMsg_OK    PullSrvMsg_Code = 1
	PullSrvMsg_ERROR PullSrvMsg_Code = 2
)

// Enum value maps for PullSrvMsg_Code.
var (
	PullSrvMsg_Code_name = map[int32]string{
		0: "START",
		1: "OK",
		2: "ERROR",
	}
	PullSrvMsg_Code_value = map[string]int32{
		"START": 0,
		"OK":    1,
		"ERROR": 2,
	}
)

func (x PullSrvMsg_Code) Enum() *PullSrvMsg_Code {
	p := new(PullSrvMsg_Code)
	*p = x
	return p
}

func (x PullSrvMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullSrvMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[5].Descriptor()
}

func (PullSrvMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[5]
}

func (x PullSrvMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullSrvMsg_Code.Descriptor instead.
func (PullSrvMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{3, 0}
}

type CaptureSrvMsg_Code int32

const (
	CaptureSrvMsg_STDOUT CaptureSrvMsg_Code = 0
	CaptureSrvMsg_STDERR CaptureSrvMsg_Code = 1
	CaptureSrvMsg_OK     CaptureSrvMsg_Code = 2
	CaptureSrvMsg_ERROR  CaptureSrvMsg_Code = 3
)

// Enum value maps for CaptureSrvMsg_Code.
var (
	CaptureSrvMsg_Code_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "OK",
		3: "ERROR",
	}
	CaptureSrvMsg_Code_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"OK":     2,
		"ERROR":  3,
	}
)

func (x CaptureSrvMsg_Code) Enum() *CaptureSrvMsg_Code {
	p := new(CaptureSrvMsg_Code)
	*p = x
	return p
}

func (x CaptureSrvMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaptureSrvMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[6].Descriptor()
}

func (CaptureSrvMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[6]
}

func (x CaptureSrvMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaptureSrvMsg_Code.Descriptor instead.
func (CaptureSrvMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{4, 0}
}

type TopologyRunMsg_Code int32

const (
	TopologyRunMsg_NODE_COUNT      TopologyRunMsg_Code = 0
	TopologyRunMsg_BRIDGE_COUNT    TopologyRunMsg_Code = 1
	TopologyRunMsg_LINK_COUNT      TopologyRunMsg_Code = 2
	TopologyRunMsg_NODE_START      TopologyRunMsg_Code = 3
	TopologyRunMsg_LINK_SETUP      TopologyRunMsg_Code = 4
	TopologyRunMsg_BRIDGE_START    TopologyRunMsg_Code = 5
	TopologyRunMsg_NODE_LOADCONFIG TopologyRunMsg_Code = 6
	TopologyRunMsg_NODE_MESSAGES   TopologyRunMsg_Code = 7
	TopologyRunMsg_NODE_STOP       TopologyRunMsg_Code = 8
	TopologyRunMsg_NODE_RM         TopologyRunMsg_Code = 9
)

// Enum value maps for TopologyRunMsg_Code.
var (
	TopologyRunMsg_Code_name = map[int32]string{
		0: "NODE_COUNT",
		1: "BRIDGE_COUNT",
		2: "LINK_COUNT",
		3: "NODE_START",
		4: "LINK_SETUP",
		5: "BRIDGE_START",
		6: "NODE_LOADCONFIG",
		7: "NODE_MESSAGES",
		8: "NODE_STOP",
		9: "NODE_RM",
	}
	TopologyRunMsg_Code_value = map[string]int32{
		"NODE_COUNT":      0,
		"BRIDGE_COUNT":    1,
		"LINK_COUNT":      2,
		"NODE_START":      3,
		"LINK_SETUP":      4,
		"BRIDGE_START":    5,
		"NODE_LOADCONFIG": 6,
		"NODE_MESSAGES":   7,
		"NODE_STOP":       8,
		"NODE_RM":         9,
	}
)

func (x TopologyRunMsg_Code) Enum() *TopologyRunMsg_Code {
	p := new(TopologyRunMsg_Code)
	*p = x
	return p
}

func (x TopologyRunMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopologyRunMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[7].Descriptor()
}

func (TopologyRunMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[7]
}

func (x TopologyRunMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopologyRunMsg_Code.Descriptor instead.
func (TopologyRunMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{5, 0}
}

type ProjectSaveMsg_Code int32

const (
	ProjectSaveMsg_NODE_COUNT ProjectSaveMsg_Code = 0
	ProjectSaveMsg_NODE_SAVE  ProjectSaveMsg_Code = 1
	ProjectSaveMsg_DATA       ProjectSaveMsg_Code = 2
)

// Enum value maps for ProjectSaveMsg_Code.
var (
	ProjectSaveMsg_Code_name = map[int32]string{
		0: "NODE_COUNT",
		1: "NODE_SAVE",
		2: "DATA",
	}
	ProjectSaveMsg_Code_value = map[string]int32{
		"NODE_COUNT": 0,
		"NODE_SAVE":  1,
		"DATA":       2,
	}
)

func (x ProjectSaveMsg_Code) Enum() *ProjectSaveMsg_Code {
	p := new(ProjectSaveMsg_Code)
	*p = x
	return p
}

func (x ProjectSaveMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectSaveMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[8].Descriptor()
}

func (ProjectSaveMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[8]
}

func (x ProjectSaveMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectSaveMsg_Code.Descriptor instead.
func (ProjectSaveMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{6, 0}
}

type ProjectCloseMsg_Code int32

const (
	ProjectCloseMsg_NODE_COUNT   ProjectCloseMsg_Code = 0
	ProjectCloseMsg_BRIDGE_COUNT ProjectCloseMsg_Code = 1
	ProjectCloseMsg_NODE_CLOSE   ProjectCloseMsg_Code = 2
	ProjectCloseMsg_BRIDGE_CLOSE ProjectCloseMsg_Code = 3
)

// Enum value maps for ProjectCloseMsg_Code.
var (
	ProjectCloseMsg_Code_name = map[int32]string{
		0: "NODE_COUNT",
		1: "BRIDGE_COUNT",
		2: "NODE_CLOSE",
		3: "BRIDGE_CLOSE",
	}
	ProjectCloseMsg_Code_value = map[string]int32{
		"NODE_COUNT":   0,
		"BRIDGE_COUNT": 1,
		"NODE_CLOSE":   2,
		"BRIDGE_CLOSE": 3,
	}
)

func (x ProjectCloseMsg_Code) Enum() *ProjectCloseMsg_Code {
	p := new(ProjectCloseMsg_Code)
	*p = x
	return p
}

func (x ProjectCloseMsg_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectCloseMsg_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[9].Descriptor()
}

func (ProjectCloseMsg_Code) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[9]
}

func (x ProjectCloseMsg_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectCloseMsg_Code.Descriptor instead.
func (ProjectCloseMsg_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{7, 0}
}

type ConfigFilesResponse_Source int32

const (
	ConfigFilesResponse_ARCHIVE ConfigFilesResponse_Source = 0
	ConfigFilesResponse_RUNNING ConfigFilesResponse_Source = 1
)

// Enum value maps for ConfigFilesResponse_Source.
var (
	ConfigFilesResponse_Source_name = map[int32]string{
		0: "ARCHIVE",
		1: "RUNNING",
	}
	ConfigFilesResponse_Source_value = map[string]int32{
		"ARCHIVE": 0,
		"RUNNING": 1,
	}
)

func (x ConfigFilesResponse_Source) Enum() *ConfigFilesResponse_Source {
	p := new(ConfigFilesResponse_Source)
	*p = x
	return p
}

func (x ConfigFilesResponse_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFilesResponse_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_netem_proto_enumTypes[10].Descriptor()
}

func (ConfigFilesResponse_Source) Type() protoreflect.EnumType {
	return &file_internal_proto_netem_proto_enumTypes[10]
}

func (x ConfigFilesResponse_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFilesResponse_Source.Descriptor instead.
func (ConfigFilesResponse_Source) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{23, 0}
}

type ExecCltMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ExecCltMsg_Code        `protobuf:"varint,1,opt,name=code,proto3,enum=netem.ExecCltMsg_Code" json:"code,omitempty"`
	PrjId         string                 `protobuf:"bytes,2,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Cmd           []string               `protobuf:"bytes,4,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Tty           bool                   `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	TtyWidth      int32                  `protobuf:"varint,7,opt,name=ttyWidth,proto3" json:"ttyWidth,omitempty"`
	TtyHeight     int32                  `protobuf:"varint,8,opt,name=ttyHeight,proto3" json:"ttyHeight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCltMsg) Reset() {
	*x = ExecCltMsg{}
	mi := &file_internal_proto_netem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCltMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCltMsg) ProtoMessage() {}

func (x *ExecCltMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCltMsg.ProtoReflect.Descriptor instead.
func (*ExecCltMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{0}
}

func (x *ExecCltMsg) GetCode() ExecCltMsg_Code {
	if x != nil {
		return x.Code
	}
	return ExecCltMsg_CMD
}

func (x *ExecCltMsg) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *ExecCltMsg) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ExecCltMsg) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ExecCltMsg) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecCltMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecCltMsg) GetTtyWidth() int32 {
	if x != nil {
		return x.TtyWidth
	}
	return 0
}

func (x *ExecCltMsg) GetTtyHeight() int32 {
	if x != nil {
		return x.TtyHeight
	}
	return 0
}

type ExecSrvMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ExecSrvMsg_Code        `protobuf:"varint,1,opt,name=code,proto3,enum=netem.ExecSrvMsg_Code" json:"code,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSrvMsg) Reset() {
	*x = ExecSrvMsg{}
	mi := &file_internal_proto_netem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSrvMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSrvMsg) ProtoMessage() {}

func (x *ExecSrvMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSrvMsg.ProtoReflect.Descriptor instead.
func (*ExecSrvMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{1}
}

func (x *ExecSrvMsg) GetCode() ExecSrvMsg_Code {
	if x != nil {
		return x.Code
	}
	return ExecSrvMsg_STDOUT
}

func (x *ExecSrvMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CopyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          CopyMsg_Code           `protobuf:"varint,1,opt,name=code,proto3,enum=netem.CopyMsg_Code" json:"code,omitempty"`
	PrjId         string                 `protobuf:"bytes,2,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	NodePath      string                 `protobuf:"bytes,4,opt,name=nodePath,proto3" json:"nodePath,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyMsg) Reset() {
	*x = CopyMsg{}
	mi := &file_internal_proto_netem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyMsg) ProtoMessage() {}

func (x *CopyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyMsg.ProtoReflect.Descriptor instead.
func (*CopyMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{2}
}

func (x *CopyMsg) GetCode() CopyMsg_Code {
	if x != nil {
		return x.Code
	}
	return CopyMsg_INIT
}

func (x *CopyMsg) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *CopyMsg) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *CopyMsg) GetNodePath() string {
	if x != nil {
		return x.NodePath
	}
	return ""
}

func (x *CopyMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PullSrvMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          PullSrvMsg_Code        `protobuf:"varint,1,opt,name=code,proto3,enum=netem.PullSrvMsg_Code" json:"code,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullSrvMsg) Reset() {
	*x = PullSrvMsg{}
	mi := &file_internal_proto_netem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullSrvMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullSrvMsg) ProtoMessage() {}

func (x *PullSrvMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullSrvMsg.ProtoReflect.Descriptor instead.
func (*PullSrvMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{3}
}

func (x *PullSrvMsg) GetCode() PullSrvMsg_Code {
	if x != nil {
		return x.Code
	}
	return PullSrvMsg_START
}

func (x *PullSrvMsg) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PullSrvMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CaptureSrvMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          CaptureSrvMsg_Code     `protobuf:"varint,1,opt,name=code,proto3,enum=netem.CaptureSrvMsg_Code" json:"code,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureSrvMsg) Reset() {
	*x = CaptureSrvMsg{}
	mi := &file_internal_proto_netem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSrvMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSrvMsg) ProtoMessage() {}

func (x *CaptureSrvMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSrvMsg.ProtoReflect.Descriptor instead.
func (*CaptureSrvMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureSrvMsg) GetCode() CaptureSrvMsg_Code {
	if x != nil {
		return x.Code
	}
	return CaptureSrvMsg_STDOUT
}

func (x *CaptureSrvMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TopologyRunMsg struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          TopologyRunMsg_Code            `protobuf:"varint,1,opt,name=code,proto3,enum=netem.TopologyRunMsg_Code" json:"code,omitempty"`
	Total         int32                          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NodeMessages  []*TopologyRunMsg_NodeMessages `protobuf:"bytes,3,rep,name=nodeMessages,proto3" json:"nodeMessages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRunMsg) Reset() {
	*x = TopologyRunMsg{}
	mi := &file_internal_proto_netem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRunMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRunMsg) ProtoMessage() {}

func (x *TopologyRunMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRunMsg.ProtoReflect.Descriptor instead.
func (*TopologyRunMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{5}
}

func (x *TopologyRunMsg) GetCode() TopologyRunMsg_Code {
	if x != nil {
		return x.Code
	}
	return TopologyRunMsg_NODE_COUNT
}

func (x *TopologyRunMsg) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TopologyRunMsg) GetNodeMessages() []*TopologyRunMsg_NodeMessages {
	if x != nil {
		return x.NodeMessages
	}
	return nil
}

type ProjectSaveMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ProjectSaveMsg_Code    `protobuf:"varint,1,opt,name=code,proto3,enum=netem.ProjectSaveMsg_Code" json:"code,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSaveMsg) Reset() {
	*x = ProjectSaveMsg{}
	mi := &file_internal_proto_netem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSaveMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSaveMsg) ProtoMessage() {}

func (x *ProjectSaveMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSaveMsg.ProtoReflect.Descriptor instead.
func (*ProjectSaveMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectSaveMsg) GetCode() ProjectSaveMsg_Code {
	if x != nil {
		return x.Code
	}
	return ProjectSaveMsg_NODE_COUNT
}

func (x *ProjectSaveMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProjectSaveMsg) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ProjectCloseMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ProjectCloseMsg_Code   `protobuf:"varint,1,opt,name=code,proto3,enum=netem.ProjectCloseMsg_Code" json:"code,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCloseMsg) Reset() {
	*x = ProjectCloseMsg{}
	mi := &file_internal_proto_netem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCloseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCloseMsg) ProtoMessage() {}

func (x *ProjectCloseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCloseMsg.ProtoReflect.Descriptor instead.
func (*ProjectCloseMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectCloseMsg) GetCode() ProjectCloseMsg_Code {
	if x != nil {
		return x.Code
	}
	return ProjectCloseMsg_NODE_COUNT
}

func (x *ProjectCloseMsg) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LinkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer1         string                 `protobuf:"bytes,1,opt,name=peer1,proto3" json:"peer1,omitempty"`
	Peer2         string                 `protobuf:"bytes,2,opt,name=peer2,proto3" json:"peer2,omitempty"`
	Peer1Qos      *LinkConfig_QoSConfig  `protobuf:"bytes,3,opt,name=peer1qos,proto3" json:"peer1qos,omitempty"`
	Peer2Qos      *LinkConfig_QoSConfig  `protobuf:"bytes,4,opt,name=peer2qos,proto3" json:"peer2qos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkConfig) Reset() {
	*x = LinkConfig{}
	mi := &file_internal_proto_netem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkConfig) ProtoMessage() {}

func (x *LinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkConfig.ProtoReflect.Descriptor instead.
func (*LinkConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{8}
}

func (x *LinkConfig) GetPeer1() string {
	if x != nil {
		return x.Peer1
	}
	return ""
}

func (x *LinkConfig) GetPeer2() string {
	if x != nil {
		return x.Peer2
	}
	return ""
}

func (x *LinkConfig) GetPeer1Qos() *LinkConfig_QoSConfig {
	if x != nil {
		return x.Peer1Qos
	}
	return nil
}

func (x *LinkConfig) GetPeer2Qos() *LinkConfig_QoSConfig {
	if x != nil {
		return x.Peer2Qos
	}
	return nil
}

type LinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrjId         string                 `protobuf:"bytes,1,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Link          *LinkConfig            `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Sync          bool                   `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkRequest) Reset() {
	*x = LinkRequest{}
	mi := &file_internal_proto_netem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequest) ProtoMessage() {}

func (x *LinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequest.ProtoReflect.Descriptor instead.
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{9}
}

func (x *LinkRequest) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *LinkRequest) GetLink() *LinkConfig {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *LinkRequest) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type NodeIfStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrjId         string                 `protobuf:"bytes,1,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	IfIndex       int32                  `protobuf:"varint,3,opt,name=ifIndex,proto3" json:"ifIndex,omitempty"`
	State         IfState                `protobuf:"varint,4,opt,name=state,proto3,enum=netem.IfState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIfStateRequest) Reset() {
	*x = NodeIfStateRequest{}
	mi := &file_internal_proto_netem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIfStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIfStateRequest) ProtoMessage() {}

func (x *NodeIfStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIfStateRequest.ProtoReflect.Descriptor instead.
func (*NodeIfStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{10}
}

func (x *NodeIfStateRequest) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *NodeIfStateRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeIfStateRequest) GetIfIndex() int32 {
	if x != nil {
		return x.IfIndex
	}
	return 0
}

func (x *NodeIfStateRequest) GetState() IfState {
	if x != nil {
		return x.State
	}
	return IfState_UP
}

type NodeInterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrjId         string                 `protobuf:"bytes,1,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	IfIndex       int32                  `protobuf:"varint,3,opt,name=ifIndex,proto3" json:"ifIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInterfaceRequest) Reset() {
	*x = NodeInterfaceRequest{}
	mi := &file_internal_proto_netem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInterfaceRequest) ProtoMessage() {}

func (x *NodeInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInterfaceRequest.ProtoReflect.Descriptor instead.
func (*NodeInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{11}
}

func (x *NodeInterfaceRequest) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *NodeInterfaceRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeInterfaceRequest) GetIfIndex() int32 {
	if x != nil {
		return x.IfIndex
	}
	return 0
}

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrjId         string                 `protobuf:"bytes,1,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_internal_proto_netem_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{12}
}

func (x *NodeRequest) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *NodeRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type ConsoleCmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrjId         string                 `protobuf:"bytes,1,opt,name=prjId,proto3" json:"prjId,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Shell         bool                   `protobuf:"varint,3,opt,name=shell,proto3" json:"shell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleCmdRequest) Reset() {
	*x = ConsoleCmdRequest{}
	mi := &file_internal_proto_netem_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCmdRequest) ProtoMessage() {}

func (x *ConsoleCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCmdRequest.ProtoReflect.Descriptor instead.
func (*ConsoleCmdRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{13}
}

func (x *ConsoleCmdRequest) GetPrjId() string {
	if x != nil {
		return x.PrjId
	}
	return ""
}

func (x *ConsoleCmdRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ConsoleCmdRequest) GetShell() bool {
	if x != nil {
		return x.Shell
	}
	return false
}

type ProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	mi := &file_internal_proto_netem_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{14}
}

func (x *ProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WNetworkRequest) Reset() {
	*x = WNetworkRequest{}
	mi := &file_internal_proto_netem_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WNetworkRequest) ProtoMessage() {}

func (x *WNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WNetworkRequest.ProtoReflect.Descriptor instead.
func (*WNetworkRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{15}
}

func (x *WNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WNetworkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_internal_proto_netem_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{16}
}

func (x *OpenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=netem.StatusCode" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_internal_proto_netem_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{17}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_OK
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_internal_proto_netem_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{18}
}

func (x *AckResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_internal_proto_netem_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{19}
}

func (x *FileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_internal_proto_netem_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{20}
}

func (x *VersionResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ConsoleCmdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Cmd           []string               `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleCmdResponse) Reset() {
	*x = ConsoleCmdResponse{}
	mi := &file_internal_proto_netem_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCmdResponse) ProtoMessage() {}

func (x *ConsoleCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCmdResponse.ProtoReflect.Descriptor instead.
func (*ConsoleCmdResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{21}
}

func (x *ConsoleCmdResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ConsoleCmdResponse) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        *Status                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                       `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	OpenAt        string                       `protobuf:"bytes,4,opt,name=openAt,proto3" json:"openAt,omitempty"`
	Running       bool                         `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	Nodes         []*StatusResponse_NodeStatus `protobuf:"bytes,10,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_proto_netem_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{22}
}

func (x *StatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusResponse) GetOpenAt() string {
	if x != nil {
		return x.OpenAt
	}
	return ""
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetNodes() []*StatusResponse_NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ConfigFilesResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        *Status                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Source        ConfigFilesResponse_Source        `protobuf:"varint,2,opt,name=source,proto3,enum=netem.ConfigFilesResponse_Source" json:"source,omitempty"`
	Files         []*ConfigFilesResponse_ConfigFile `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFilesResponse) Reset() {
	*x = ConfigFilesResponse{}
	mi := &file_internal_proto_netem_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFilesResponse) ProtoMessage() {}

func (x *ConfigFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFilesResponse.ProtoReflect.Descriptor instead.
func (*ConfigFilesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{23}
}

func (x *ConfigFilesResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ConfigFilesResponse) GetSource() ConfigFilesResponse_Source {
	if x != nil {
		return x.Source
	}
	return ConfigFilesResponse_ARCHIVE
}

func (x *ConfigFilesResponse) GetFiles() []*ConfigFilesResponse_ConfigFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type PrjListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        *Status                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Projects      []*PrjListResponse_Info `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrjListResponse) Reset() {
	*x = PrjListResponse{}
	mi := &file_internal_proto_netem_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrjListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrjListResponse) ProtoMessage() {}

func (x *PrjListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrjListResponse.ProtoReflect.Descriptor instead.
func (*PrjListResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{24}
}

func (x *PrjListResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PrjListResponse) GetProjects() []*PrjListResponse_Info {
	if x != nil {
		return x.Projects
	}
	return nil
}

type PrjOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrjOpenResponse) Reset() {
	*x = PrjOpenResponse{}
	mi := &file_internal_proto_netem_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrjOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrjOpenResponse) ProtoMessage() {}

func (x *PrjOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrjOpenResponse.ProtoReflect.Descriptor instead.
func (*PrjOpenResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{25}
}

func (x *PrjOpenResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PrjOpenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TopologyRunMsg_NodeMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Messages      []string               `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRunMsg_NodeMessages) Reset() {
	*x = TopologyRunMsg_NodeMessages{}
	mi := &file_internal_proto_netem_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRunMsg_NodeMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRunMsg_NodeMessages) ProtoMessage() {}

func (x *TopologyRunMsg_NodeMessages) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRunMsg_NodeMessages.ProtoReflect.Descriptor instead.
func (*TopologyRunMsg_NodeMessages) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{5, 0}
}

func (x *TopologyRunMsg_NodeMessages) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopologyRunMsg_NodeMessages) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type LinkConfig_QoSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loss          float32                `protobuf:"fixed32,3,opt,name=loss,proto3" json:"loss,omitempty"`
	Delay         int32                  `protobuf:"varint,4,opt,name=delay,proto3" json:"delay,omitempty"`
	Jitter        int32                  `protobuf:"varint,5,opt,name=jitter,proto3" json:"jitter,omitempty"`
	Rate          int32                  `protobuf:"varint,6,opt,name=rate,proto3" json:"rate,omitempty"`
	Buffer        float32                `protobuf:"fixed32,7,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Burst         int32                  `protobuf:"varint,8,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkConfig_QoSConfig) Reset() {
	*x = LinkConfig_QoSConfig{}
	mi := &file_internal_proto_netem_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkConfig_QoSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkConfig_QoSConfig) ProtoMessage() {}

func (x *LinkConfig_QoSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkConfig_QoSConfig.ProtoReflect.Descriptor instead.
func (*LinkConfig_QoSConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{8, 0}
}

func (x *LinkConfig_QoSConfig) GetLoss() float32 {
	if x != nil {
		return x.Loss
	}
	return 0
}

func (x *LinkConfig_QoSConfig) GetDelay() int32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *LinkConfig_QoSConfig) GetJitter() int32 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *LinkConfig_QoSConfig) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *LinkConfig_QoSConfig) GetBuffer() float32 {
	if x != nil {
		return x.Buffer
	}
	return 0
}

func (x *LinkConfig_QoSConfig) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type StatusResponse_IfStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         IfState                `protobuf:"varint,2,opt,name=state,proto3,enum=netem.IfState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse_IfStatus) Reset() {
	*x = StatusResponse_IfStatus{}
	mi := &file_internal_proto_netem_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse_IfStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse_IfStatus) ProtoMessage() {}

func (x *StatusResponse_IfStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse_IfStatus.ProtoReflect.Descriptor instead.
func (*StatusResponse_IfStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{22, 0}
}

func (x *StatusResponse_IfStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusResponse_IfStatus) GetState() IfState {
	if x != nil {
		return x.State
	}
	return IfState_UP
}

type StatusResponse_NodeStatus struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Running       bool                       `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Interfaces    []*StatusResponse_IfStatus `protobuf:"bytes,10,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse_NodeStatus) Reset() {
	*x = StatusResponse_NodeStatus{}
	mi := &file_internal_proto_netem_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse_NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse_NodeStatus) ProtoMessage() {}

func (x *StatusResponse_NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse_NodeStatus.ProtoReflect.Descriptor instead.
func (*StatusResponse_NodeStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{22, 1}
}

func (x *StatusResponse_NodeStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusResponse_NodeStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse_NodeStatus) GetInterfaces() []*StatusResponse_IfStatus {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type ConfigFilesResponse_ConfigFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFilesResponse_ConfigFile) Reset() {
	*x = ConfigFilesResponse_ConfigFile{}
	mi := &file_internal_proto_netem_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFilesResponse_ConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFilesResponse_ConfigFile) ProtoMessage() {}

func (x *ConfigFilesResponse_ConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFilesResponse_ConfigFile.ProtoReflect.Descriptor instead.
func (*ConfigFilesResponse_ConfigFile) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{23, 0}
}

func (x *ConfigFilesResponse_ConfigFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigFilesResponse_ConfigFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PrjListResponse_Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OpenAt        string                 `protobuf:"bytes,3,opt,name=openAt,proto3" json:"openAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrjListResponse_Info) Reset() {
	*x = PrjListResponse_Info{}
	mi := &file_internal_proto_netem_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrjListResponse_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrjListResponse_Info) ProtoMessage() {}

func (x *PrjListResponse_Info) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_netem_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrjListResponse_Info.ProtoReflect.Descriptor instead.
func (*PrjListResponse_Info) Descriptor() ([]byte, []int) {
	return file_internal_proto_netem_proto_rawDescGZIP(), []int{24, 0}
}

func (x *PrjListResponse_Info) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrjListResponse_Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PrjListResponse_Info) GetOpenAt() string {
	if x != nil {
		return x.OpenAt
	}
	return ""
}

var File_internal_proto_netem_proto protoreflect.FileDescriptor

const file_internal_proto_netem_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/netem.proto\x12\x05netem\x1a\x1bgoogle/protobuf/empty.proto\"\x91\x02\n" +
	"\n" +
	"ExecCltMsg\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.netem.ExecCltMsg.CodeR\x04code\x12\x14\n" +
	"\x05prjId\x18\x02 \x01(\tR\x05prjId\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x10\n" +
	"\x03cmd\x18\x04 \x03(\tR\x03cmd\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1a\n" +
	"\bttyWidth\x18\a \x01(\x05R\bttyWidth\x12\x1c\n" +
	"\tttyHeight\x18\b \x01(\x05R\tttyHeight\";\n" +
	"\x04Code\x12\a\n" +
	"\x03CMD\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\n" +
	"\n" +
	"\x06RESIZE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\t\n" +
	"\x05CLOSE\x10\x04\"\x82\x01\n" +
	"\n" +
	"ExecSrvMsg\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.netem.ExecSrvMsg.CodeR\x04code\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"4\n" +
	"\x04Code\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\t\n" +
	"\x05CLOSE\x10\x03\"\xb3\x01\n" +
	"\aCopyMsg\x12'\n" +
	"\x04code\x18\x01 \x01(\x0e2\x13.netem.CopyMsg.CodeR\x04code\x12\x14\n" +
	"\x05prjId\x18\x02 \x01(\tR\x05prjId\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x1a\n" +
	"\bnodePath\x18\x04 \x01(\tR\bnodePath\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"%\n" +
	"\x04Code\x12\b\n" +
	"\x04INIT\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x03\"\x8a\x01\n" +
	"\n" +
	"PullSrvMsg\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.netem.PullSrvMsg.CodeR\x04code\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"$\n" +
	"\x04Code\x12\t\n" +
	"\x05START\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\"\x85\x01\n" +
	"\rCaptureSrvMsg\x12-\n" +
	"\x04code\x18\x01 \x01(\x0e2\x19.netem.CaptureSrvMsg.CodeR\x04code\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"1\n" +
	"\x04Code\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\x06\n" +
	"\x02OK\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"\x8f\x03\n" +
	"\x0eTopologyRunMsg\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.netem.TopologyRunMsg.CodeR\x04code\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12F\n" +
	"\fnodeMessages\x18\x03 \x03(\v2\".netem.TopologyRunMsg.NodeMessagesR\fnodeMessages\x1a>\n" +
	"\fNodeMessages\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bmessages\x18\x02 \x03(\tR\bmessages\"\xae\x01\n" +
	"\x04Code\x12\x0e\n" +
	"\n" +
	"NODE_COUNT\x10\x00\x12\x10\n" +
	"\fBRIDGE_COUNT\x10\x01\x12\x0e\n" +
	"\n" +
	"LINK_COUNT\x10\x02\x12\x0e\n" +
	"\n" +
	"NODE_START\x10\x03\x12\x0e\n" +
	"\n" +
	"LINK_SETUP\x10\x04\x12\x10\n" +
	"\fBRIDGE_START\x10\x05\x12\x13\n" +
	"\x0fNODE_LOADCONFIG\x10\x06\x12\x11\n" +
	"\rNODE_MESSAGES\x10\a\x12\r\n" +
	"\tNODE_STOP\x10\b\x12\v\n" +
	"\aNODE_RM\x10\t\"\x9b\x01\n" +
	"\x0eProjectSaveMsg\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.netem.ProjectSaveMsg.CodeR\x04code\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"/\n" +
	"\x04Code\x12\x0e\n" +
	"\n" +
	"NODE_COUNT\x10\x00\x12\r\n" +
	"\tNODE_SAVE\x10\x01\x12\b\n" +
	"\x04DATA\x10\x02\"\xa4\x01\n" +
	"\x0fProjectCloseMsg\x12/\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1b.netem.ProjectCloseMsg.CodeR\x04code\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"J\n" +
	"\x04Code\x12\x0e\n" +
	"\n" +
	"NODE_COUNT\x10\x00\x12\x10\n" +
	"\fBRIDGE_COUNT\x10\x01\x12\x0e\n" +
	"\n" +
	"NODE_CLOSE\x10\x02\x12\x10\n" +
	"\fBRIDGE_CLOSE\x10\x03\"\xbc\x02\n" +
	"\n" +
	"LinkConfig\x12\x14\n" +
	"\x05peer1\x18\x01 \x01(\tR\x05peer1\x12\x14\n" +
	"\x05peer2\x18\x02 \x01(\tR\x05peer2\x127\n" +
	"\bpeer1qos\x18\x03 \x01(\v2\x1b.netem.LinkConfig.QoSConfigR\bpeer1qos\x127\n" +
	"\bpeer2qos\x18\x04 \x01(\v2\x1b.netem.LinkConfig.QoSConfigR\bpeer2qos\x1a\x8f\x01\n" +
	"\tQoSConfig\x12\x12\n" +
	"\x04loss\x18\x03 \x01(\x02R\x04loss\x12\x14\n" +
	"\x05delay\x18\x04 \x01(\x05R\x05delay\x12\x16\n" +
	"\x06jitter\x18\x05 \x01(\x05R\x06jitter\x12\x12\n" +
	"\x04rate\x18\x06 \x01(\x05R\x04rate\x12\x16\n" +
	"\x06buffer\x18\a \x01(\x02R\x06buffer\x12\x14\n" +
	"\x05burst\x18\b \x01(\x05R\x05burst\"^\n" +
	"\vLinkRequest\x12\x14\n" +
	"\x05prjId\x18\x01 \x01(\tR\x05prjId\x12%\n" +
	"\x04link\x18\x02 \x01(\v2\x11.netem.LinkConfigR\x04link\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\bR\x04sync\"~\n" +
	"\x12NodeIfStateRequest\x12\x14\n" +
	"\x05prjId\x18\x01 \x01(\tR\x05prjId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x18\n" +
	"\aifIndex\x18\x03 \x01(\x05R\aifIndex\x12$\n" +
	"\x05state\x18\x04 \x01(\x0e2\x0e.netem.IfStateR\x05state\"Z\n" +
	"\x14NodeInterfaceRequest\x12\x14\n" +
	"\x05prjId\x18\x01 \x01(\tR\x05prjId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x18\n" +
	"\aifIndex\x18\x03 \x01(\x05R\aifIndex\"7\n" +
	"\vNodeRequest\x12\x14\n" +
	"\x05prjId\x18\x01 \x01(\tR\x05prjId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\"S\n" +
	"\x11ConsoleCmdRequest\x12\x14\n" +
	"\x05prjId\x18\x01 \x01(\tR\x05prjId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x14\n" +
	"\x05shell\x18\x03 \x01(\bR\x05shell\" \n" +
	"\x0eProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fWNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"5\n" +
	"\vOpenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"E\n" +
	"\x06Status\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.netem.StatusCodeR\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\vAckResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\v2\r.netem.StatusR\x06status\"I\n" +
	"\fFileResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\v2\r.netem.StatusR\x06status\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"R\n" +
	"\x0fVersionResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\v2\r.netem.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"M\n" +
	"\x12ConsoleCmdResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\v2\r.netem.StatusR\x06status\x12\x10\n" +
	"\x03cmd\x18\x02 \x03(\tR\x03cmd\"\x87\x03\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\v2\r.netem.StatusR\x06status\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x16\n" +
	"\x06openAt\x18\x04 \x01(\tR\x06openAt\x12\x18\n" +
	"\arunning\x18\x05 \x01(\bR\arunning\x126\n" +
	"\x05nodes\x18\n" +
	" \x03(\v2 .netem.StatusResponse.NodeStatusR\x05nodes\x1aD\n" +
	"\bIfStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x05state\x18\x02 \x01(\x0e2\x0e.netem.IfStateR\x05state\x1az\n" +
	"\n" +
	"NodeStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12>\n" +
	"\n" +
	"interfaces\x18\n" +
	" \x03(\v2\x1e.netem.StatusResponse.IfStatusR\n" +
	"interfaces\"\x8e\x02\n" +
	"\x13ConfigFilesResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\v2\r.netem.StatusR\x06status\x129\n" +
	"\x06source\x18\x02 \x01(\x0e2!.netem.ConfigFilesResponse.SourceR\x06source\x12;\n" +
	"\x05files\x18\x03 \x03(\v2%.netem.ConfigFilesResponse.ConfigFileR\x05files\x1a4\n" +
	"\n" +
	"ConfigFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\"\n" +
	"\x06Source\x12\v\n" +
	"\aARCHIVE\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\"\xb5\x01\n" +
	"\x0fPrjListResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\v2\r.netem.StatusR\x06status\x127\n" +
	"\bprojects\x18\x02 \x03(\v2\x1b.netem.PrjListResponse.InfoR\bprojects\x1aB\n" +
	"\x04Info\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06openAt\x18\x03 \x01(\tR\x06openAt\"H\n" +
	"\x0fPrjOpenResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\v2\r.netem.StatusR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id*\x1f\n" +
	"\n" +
	"StatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01*\x1b\n" +
	"\aIfState\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x012\xb6\x0e\n" +
	"\x05Netem\x12D\n" +
	"\x10ServerGetVersion\x12\x16.google.protobuf.Empty\x1a\x16.netem.VersionResponse\"\x00\x12A\n" +
	"\x10ServerPullImages\x12\x16.google.protobuf.Empty\x1a\x11.netem.PullSrvMsg\"\x000\x01\x12E\n" +
	"\x15ServerCleanContainers\x12\x16.google.protobuf.Empty\x1a\x12.netem.AckResponse\"\x00\x12B\n" +
	"\x0eProjectGetMany\x12\x16.google.protobuf.Empty\x1a\x16.netem.PrjListResponse\"\x00\x12;\n" +
	"\vProjectOpen\x12\x12.netem.OpenRequest\x1a\x16.netem.PrjOpenResponse\"\x00\x12A\n" +
	"\fProjectClose\x12\x15.netem.ProjectRequest\x1a\x16.netem.ProjectCloseMsg\"\x000\x01\x12?\n" +
	"\vProjectSave\x12\x15.netem.ProjectRequest\x1a\x15.netem.ProjectSaveMsg\"\x000\x01\x12E\n" +
	"\x15ProjectGetNodeConfigs\x12\x15.netem.ProjectRequest\x1a\x13.netem.FileResponse\"\x00\x12B\n" +
	"\x10ProjectGetStatus\x12\x15.netem.ProjectRequest\x1a\x15.netem.StatusResponse\"\x00\x12?\n" +
	"\x0fReadNetworkFile\x12\x15.netem.ProjectRequest\x1a\x13.netem.FileResponse\"\x00\x12@\n" +
	"\x10WriteNetworkFile\x12\x16.netem.WNetworkRequest\x1a\x12.netem.AckResponse\"\x00\x12<\n" +
	"\rTopologyCheck\x12\x15.netem.ProjectRequest\x1a\x12.netem.AckResponse\"\x00\x12B\n" +
	"\x0eTopologyReload\x12\x15.netem.ProjectRequest\x1a\x15.netem.TopologyRunMsg\"\x000\x01\x12?\n" +
	"\vTopologyRun\x12\x15.netem.ProjectRequest\x1a\x15.netem.TopologyRunMsg\"\x000\x01\x12?\n" +
	"\x10TopologyStartAll\x12\x15.netem.ProjectRequest\x1a\x12.netem.AckResponse\"\x00\x12>\n" +
	"\x0fTopologyStopAll\x12\x15.netem.ProjectRequest\x1a\x12.netem.AckResponse\"\x00\x12G\n" +
	"\x13NodeReadConfigFiles\x12\x12.netem.NodeRequest\x1a\x1a.netem.ConfigFilesResponse\"\x00\x125\n" +
	"\tNodeStart\x12\x12.netem.NodeRequest\x1a\x12.netem.AckResponse\"\x00\x124\n" +
	"\bNodeStop\x12\x12.netem.NodeRequest\x1a\x12.netem.AckResponse\"\x00\x127\n" +
	"\vNodeRestart\x12\x12.netem.NodeRequest\x1a\x12.netem.AckResponse\"\x00\x12A\n" +
	"\x0eNodeSetIfState\x12\x19.netem.NodeIfStateRequest\x1a\x12.netem.AckResponse\"\x00\x12D\n" +
	"\vNodeCapture\x12\x1b.netem.NodeInterfaceRequest\x1a\x14.netem.CaptureSrvMsg\"\x000\x01\x122\n" +
	"\fNodeCopyFrom\x12\x0e.netem.CopyMsg\x1a\x0e.netem.CopyMsg\"\x000\x01\x124\n" +
	"\n" +
	"NodeCopyTo\x12\x0e.netem.CopyMsg\x1a\x12.netem.AckResponse\"\x00(\x01\x12J\n" +
	"\x11NodeGetConsoleCmd\x12\x18.netem.ConsoleCmdRequest\x1a\x19.netem.ConsoleCmdResponse\"\x00\x126\n" +
	"\bNodeExec\x12\x11.netem.ExecCltMsg\x1a\x11.netem.ExecSrvMsg\"\x00(\x010\x01\x126\n" +
	"\n" +
	"LinkUpdate\x12\x12.netem.LinkRequest\x1a\x12.netem.AckResponse\"\x00\x123\n" +
	"\aLinkAdd\x12\x12.netem.LinkRequest\x1a\x12.netem.AckResponse\"\x00\x123\n" +
	"\aLinkDel\x12\x12.netem.LinkRequest\x1a\x12.netem.AckResponse\"\x00B*Z(github.com/mroy31/gonetem/internal/protob\x06proto3"

var (
	file_internal_proto_netem_proto_rawDescOnce sync.Once
	file_internal_proto_netem_proto_rawDescData []byte
)

func file_internal_proto_netem_proto_rawDescGZIP() []byte {
	file_internal_proto_netem_proto_rawDescOnce.Do(func() {
		file_internal_proto_netem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_netem_proto_rawDesc), len(file_internal_proto_netem_proto_rawDesc)))
	})
	return file_internal_proto_netem_proto_rawDescData
}

var file_internal_proto_netem_proto_enumTypes = make([]protoimpl.EnumInfo, 11)
var file_internal_proto_netem_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_internal_proto_netem_proto_goTypes = []any{
	(StatusCode)(0),                        // 0: netem.StatusCode
	(IfState)(0),                           // 1: netem.IfState
	(ExecCltMsg_Code)(0),                   // 2: netem.ExecCltMsg.Code
	(ExecSrvMsg_Code)(0),                   // 3: netem.ExecSrvMsg.Code
	(CopyMsg_Code)(0),                      // 4: netem.CopyMsg.Code
	(PullSrvMsg_Code)(0),                   // 5: netem.PullSrvMsg.Code
	(CaptureSrvMsg_Code)(0),                // 6: netem.CaptureSrvMsg.Code
	(TopologyRunMsg_Code)(0),               // 7: netem.TopologyRunMsg.Code
	(ProjectSaveMsg_Code)(0),               // 8: netem.ProjectSaveMsg.Code
	(ProjectCloseMsg_Code)(0),              // 9: netem.ProjectCloseMsg.Code
	(ConfigFilesResponse_Source)(0),        // 10: netem.ConfigFilesResponse.Source
	(*ExecCltMsg)(nil),                     // 11: netem.ExecCltMsg
	(*ExecSrvMsg)(nil),                     // 12: netem.ExecSrvMsg
	(*CopyMsg)(nil),                        // 13: netem.CopyMsg
	(*PullSrvMsg)(nil),                     // 14: netem.PullSrvMsg
	(*CaptureSrvMsg)(nil),                  // 15: netem.CaptureSrvMsg
	(*TopologyRunMsg)(nil),                 // 16: netem.TopologyRunMsg
	(*ProjectSaveMsg)(nil),                 // 17: netem.ProjectSaveMsg
	(*ProjectCloseMsg)(nil),                // 18: netem.ProjectCloseMsg
	(*LinkConfig)(nil),                     // 19: netem.LinkConfig
	(*LinkRequest)(nil),                    // 20: netem.LinkRequest
	(*NodeIfStateRequest)(nil),             // 21: netem.NodeIfStateRequest
	(*NodeInterfaceRequest)(nil),           // 22: netem.NodeInterfaceRequest
	(*NodeRequest)(nil),                    // 23: netem.NodeRequest
	(*ConsoleCmdRequest)(nil),              // 24: netem.ConsoleCmdRequest
	(*ProjectRequest)(nil),                 // 25: netem.ProjectRequest
	(*WNetworkRequest)(nil),                // 26: netem.WNetworkRequest
	(*OpenRequest)(nil),                    // 27: netem.OpenRequest
	(*Status)(nil),                         // 28: netem.Status
	(*AckResponse)(nil),                    // 29: netem.AckResponse
	(*FileResponse)(nil),                   // 30: netem.FileResponse
	(*VersionResponse)(nil),                // 31: netem.VersionResponse
	(*ConsoleCmdResponse)(nil),             // 32: netem.ConsoleCmdResponse
	(*StatusResponse)(nil),                 // 33: netem.StatusResponse
	(*ConfigFilesResponse)(nil),            // 34: netem.ConfigFilesResponse
	(*PrjListResponse)(nil),                // 35: netem.PrjListResponse
	(*PrjOpenResponse)(nil),                // 36: netem.PrjOpenResponse
	(*TopologyRunMsg_NodeMessages)(nil),    // 37: netem.TopologyRunMsg.NodeMessages
	(*LinkConfig_QoSConfig)(nil),           // 38: netem.LinkConfig.QoSConfig
	(*StatusResponse_IfStatus)(nil),        // 39: netem.StatusResponse.IfStatus
	(*StatusResponse_NodeStatus)(nil),      // 40: netem.StatusResponse.NodeStatus
	(*ConfigFilesResponse_ConfigFile)(nil), // 41: netem.ConfigFilesResponse.ConfigFile
	(*PrjListResponse_Info)(nil),           // 42: netem.PrjListResponse.Info
	(*empty.Empty)(nil),                    // 43: google.protobuf.Empty
}
var file_internal_proto_netem_proto_depIdxs = []int32{
	2,  // 0: netem.ExecCltMsg.code:type_name -> netem.ExecCltMsg.Code
	3,  // 1: netem.ExecSrvMsg.code:type_name -> netem.ExecSrvMsg.Code
	4,  // 2: netem.CopyMsg.code:type_name -> netem.CopyMsg.Code
	5,  // 3: netem.PullSrvMsg.code:type_name -> netem.PullSrvMsg.Code
	6,  // 4: netem.CaptureSrvMsg.code:type_name -> netem.CaptureSrvMsg.Code
	7,  // 5: netem.TopologyRunMsg.code:type_name -> netem.TopologyRunMsg.Code
	37, // 6: netem.TopologyRunMsg.nodeMessages:type_name -> netem.TopologyRunMsg.NodeMessages
	8,  // 7: netem.ProjectSaveMsg.code:type_name -> netem.ProjectSaveMsg.Code
	9,  // 8: netem.ProjectCloseMsg.code:type_name -> netem.ProjectCloseMsg.Code
	38, // 9: netem.LinkConfig.peer1qos:type_name -> netem.LinkConfig.QoSConfig
	38, // 10: netem.LinkConfig.peer2qos:type_name -> netem.LinkConfig.QoSConfig
	19, // 11: netem.LinkRequest.link:type_name -> netem.LinkConfig
	1,  // 12: netem.NodeIfStateRequest.state:type_name -> netem.IfState
	0,  // 13: netem.Status.code:type_name -> netem.StatusCode
	28, // 14: netem.AckResponse.status:type_name -> netem.Status
	28, // 15: netem.FileResponse.status:type_name -> netem.Status
	28, // 16: netem.VersionResponse.status:type_name -> netem.Status
	28, // 17: netem.ConsoleCmdResponse.status:type_name -> netem.Status
	28, // 18: netem.StatusResponse.status:type_name -> netem.Status
	40, // 19: netem.StatusResponse.nodes:type_name -> netem.StatusResponse.NodeStatus
	28, // 20: netem.ConfigFilesResponse.status:type_name -> netem.Status
	10, // 21: netem.ConfigFilesResponse.source:type_name -> netem.ConfigFilesResponse.Source
	41, // 22: netem.ConfigFilesResponse.files:type_name -> netem.ConfigFilesResponse.ConfigFile
	28, // 23: netem.PrjListResponse.status:type_name -> netem.Status
	42, // 24: netem.PrjListResponse.projects:type_name -> netem.PrjListResponse.Info
	28, // 25: netem.PrjOpenResponse.status:type_name -> netem.Status
	1,  // 26: netem.StatusResponse.IfStatus.state:type_name -> netem.IfState
	39, // 27: netem.StatusResponse.NodeStatus.interfaces:type_name -> netem.StatusResponse.IfStatus
	43, // 28: netem.Netem.ServerGetVersion:input_type -> google.protobuf.Empty
	43, // 29: netem.Netem.ServerPullImages:input_type -> google.protobuf.Empty
	43, // 30: netem.Netem.ServerCleanContainers:input_type -> google.protobuf.Empty
	43, // 31: netem.Netem.ProjectGetMany:input_type -> google.protobuf.Empty
	27, // 32: netem.Netem.ProjectOpen:input_type -> netem.OpenRequest
	25, // 33: netem.Netem.ProjectClose:input_type -> netem.ProjectRequest
	25, // 34: netem.Netem.ProjectSave:input_type -> netem.ProjectRequest
	25, // 35: netem.Netem.ProjectGetNodeConfigs:input_type -> netem.ProjectRequest
	25, // 36: netem.Netem.ProjectGetStatus:input_type -> netem.ProjectRequest
	25, // 37: netem.Netem.ReadNetworkFile:input_type -> netem.ProjectRequest
	26, // 38: netem.Netem.WriteNetworkFile:input_type -> netem.WNetworkRequest
	25, // 39: netem.Netem.TopologyCheck:input_type -> netem.ProjectRequest
	25, // 40: netem.Netem.TopologyReload:input_type -> netem.ProjectRequest
	25, // 41: netem.Netem.TopologyRun:input_type -> netem.ProjectRequest
	25, // 42: netem.Netem.TopologyStartAll:input_type -> netem.ProjectRequest
	25, // 43: netem.Netem.TopologyStopAll:input_type -> netem.ProjectRequest
	23, // 44: netem.Netem.NodeReadConfigFiles:input_type -> netem.NodeRequest
	23, // 45: netem.Netem.NodeStart:input_type -> netem.NodeRequest
	23, // 46: netem.Netem.NodeStop:input_type -> netem.NodeRequest
	23, // 47: netem.Netem.NodeRestart:input_type -> netem.NodeRequest
	21, // 48: netem.Netem.NodeSetIfState:input_type -> netem.NodeIfStateRequest
	22, // 49: netem.Netem.NodeCapture:input_type -> netem.NodeInterfaceRequest
	13, // 50: netem.Netem.NodeCopyFrom:input_type -> netem.CopyMsg
	13, // 51: netem.Netem.NodeCopyTo:input_type -> netem.CopyMsg
	24, // 52: netem.Netem.NodeGetConsoleCmd:input_type -> netem.ConsoleCmdRequest
	11, // 53: netem.Netem.NodeExec:input_type -> netem.ExecCltMsg
	20, // 54: netem.Netem.LinkUpdate:input_type -> netem.LinkRequest
	20, // 55: netem.Netem.LinkAdd:input_type -> netem.LinkRequest
	20, // 56: netem.Netem.LinkDel:input_type -> netem.LinkRequest
	31, // 57: netem.Netem.ServerGetVersion:output_type -> netem.VersionResponse
	14, // 58: netem.Netem.ServerPullImages:output_type -> netem.PullSrvMsg
	29, // 59: netem.Netem.ServerCleanContainers:output_type -> netem.AckResponse
	35, // 60: netem.Netem.ProjectGetMany:output_type -> netem.PrjListResponse
	36, // 61: netem.Netem.ProjectOpen:output_type -> netem.PrjOpenResponse
	18, // 62: netem.Netem.ProjectClose:output_type -> netem.ProjectCloseMsg
	17, // 63: netem.Netem.ProjectSave:output_type -> netem.ProjectSaveMsg
	30, // 64: netem.Netem.ProjectGetNodeConfigs:output_type -> netem.FileResponse
	33, // 65: netem.Netem.ProjectGetStatus:output_type -> netem.StatusResponse
	30, // 66: netem.Netem.ReadNetworkFile:output_type -> netem.FileResponse
	29, // 67: netem.Netem.WriteNetworkFile:output_type -> netem.AckResponse
	29, // 68: netem.Netem.TopologyCheck:output_type -> netem.AckResponse
	16, // 69: netem.Netem.TopologyReload:output_type -> netem.TopologyRunMsg
	16, // 70: netem.Netem.TopologyRun:output_type -> netem.TopologyRunMsg
	29, // 71: netem.Netem.TopologyStartAll:output_type -> netem.AckResponse
	29, // 72: netem.Netem.TopologyStopAll:output_type -> netem.AckResponse
	34, // 73: netem.Netem.NodeReadConfigFiles:output_type -> netem.ConfigFilesResponse
	29, // 74: netem.Netem.NodeStart:output_type -> netem.AckResponse
	29, // 75: netem.Netem.NodeStop:output_type -> netem.AckResponse
	29, // 76: netem.Netem.NodeRestart:output_type -> netem.AckResponse
	29, // 77: netem.Netem.NodeSetIfState:output_type -> netem.AckResponse
	15, // 78: netem.Netem.NodeCapture:output_type -> netem.CaptureSrvMsg
	13, // 79: netem.Netem.NodeCopyFrom:output_type -> netem.CopyMsg
	29, // 80: netem.Netem.NodeCopyTo:output_type -> netem.AckResponse
	32, // 81: netem.Netem.NodeGetConsoleCmd:output_type -> netem.ConsoleCmdResponse
	12, // 82: netem.Netem.NodeExec:output_type -> netem.ExecSrvMsg
	29, // 83: netem.Netem.LinkUpdate:output_type -> netem.AckResponse
	29, // 84: netem.Netem.LinkAdd:output_type -> netem.AckResponse
	29, // 85: netem.Netem.LinkDel:output_type -> netem.AckResponse
	57, // [57:86] is the sub-list for method output_type
	28, // [28:57] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_internal_proto_netem_proto_init() }
func file_internal_proto_netem_proto_init() {
	if File_internal_proto_netem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_netem_proto_rawDesc), len(file_internal_proto_netem_proto_rawDesc)),
			NumEnums:      11,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_netem_proto_goTypes,
		DependencyIndexes: file_internal_proto_netem_proto_depIdxs,
		EnumInfos:         file_internal_proto_netem_proto_enumTypes,
		MessageInfos:      file_internal_proto_netem_proto_msgTypes,
	}.Build()
	File_internal_proto_netem_proto = out.File
	file_internal_proto_netem_proto_goTypes = nil
	file_internal_proto_netem_proto_depIdxs = nil
}
